name: Build, Test, SonarQube & Snyk Security Scan

on:
  push:
    branches: [ main, backend ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  security:
    name: Snyk Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage & xUnit reporting
        run: |
          python -m pytest \
            --junitxml=../reports/junit.xml \
            --cov=app \
            --cov-report=xml:../reports/coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=backend/app
            -Dsonar.tests=backend/tests   # point directly at the tests folder
            -Dsonar.python.xunit.reportPath=../reports/junit.xml
            -Dsonar.python.coverage.reportPaths=../reports/coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}