name: Build, Test, SonarQube & Snyk Security Scan

on:
  push:
    branches: [ main, backend ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  security:
    name: Snyk Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: snyk test --all-projects

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage & xUnit reporting
        run: |
          pytest \
            --junitxml=../reports/junit.xml \
            --cov=. \
            --cov-report=xml:../reports/coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=./app
            -Dsonar.tests=./app
            -Dsonar.python.xunit.reportPath=../reports/junit.xml
            -Dsonar.python.coverage.reportPaths=../reports/coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
